// <auto-generated />
using System;
using DistributionWaterApp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DistributionWaterApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413202102_DistributionWaterInit")]
    partial class DistributionWaterInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("DistributionWaterApp.Entities.Barrio", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("CantidadCasas")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cantidad_casas");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_id");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by_id");

                    b.Property<string>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.ToTable("barrios");
                });

            modelBuilder.Entity("DistributionWaterApp.Entities.TurnoAguaEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BarrioId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("barrio_id");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_id");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha");

                    b.Property<string>("HoraFin")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_fin");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("observaciones");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by_id");

                    b.Property<string>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("BarrioId");

                    b.ToTable("turnos_agua");
                });

            modelBuilder.Entity("DistributionWaterApp.Entities.TurnoAguaEntity", b =>
                {
                    b.HasOne("DistributionWaterApp.Entities.Barrio", "Barrio")
                        .WithMany("TurnosAgua")
                        .HasForeignKey("BarrioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barrio");
                });

            modelBuilder.Entity("DistributionWaterApp.Entities.Barrio", b =>
                {
                    b.Navigation("TurnosAgua");
                });
#pragma warning restore 612, 618
        }
    }
}
