// <auto-generated />
using System;
using DistributionWaterApp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DistributionWaterApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411171423_AddDistributionWater")]
    partial class AddDistributionWater
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("DistributionWaterApp.Entities.TurnosAguaEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_id");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("observaciones");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by_id");

                    b.Property<string>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.Property<string>("ZonaId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("zona_id");

                    b.HasKey("Id");

                    b.HasIndex("ZonaId");

                    b.ToTable("turnos_agua");
                });

            modelBuilder.Entity("DistributionWaterApp.Entities.ZonaEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("CantidadCasas")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cantidad_casas");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_id");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre_zona");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by_id");

                    b.Property<string>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.ToTable("zonas");
                });

            modelBuilder.Entity("DistributionWaterApp.Entities.TurnosAguaEntity", b =>
                {
                    b.HasOne("DistributionWaterApp.Entities.ZonaEntity", "Zona")
                        .WithMany("TurnosAgua")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("DistributionWaterApp.Entities.ZonaEntity", b =>
                {
                    b.Navigation("TurnosAgua");
                });
#pragma warning restore 612, 618
        }
    }
}
